export const IPC_CHANNELS = {
  loadState: "state:load",
  saveState: "state:save",
  exportState: "state:export",
  exportAudio: "audio:export",
  importState: "state:import",
  chooseRepository: "repository:choose",
  rescanRepository: "repository:rescan",
  fullScreenState: "window:fullscreen-state",
  setFullScreen: "window:set-fullscreen",
  fullScreenChanged: "window:fullscreen-changed",
  openExternal: "shell:open-external",
  cloudStatus: "cloud:status",
  disconnectCloud: "cloud:disconnect",
  redeemCloudCode: "cloud:redeem-code",
  quoteCloudContext: "cloud:quote-context",
  analyzeCloudContext: "cloud:analyze-context",
  focusCapability: "focus:capability",
  startFocusGuardian: "focus:start",
  stopFocusGuardian: "focus:stop",
  acknowledgeFocusGuardian: "focus:acknowledge",
  focusEvent: "focus:event"
} as const;
